### ISSUE TITLE
Science Robot controller

### ISSUE THREAD

**Issue by swiftrax** [SJSURoboticsTeam/urc-electrical-2023#16]
MQ135 (CO2) and MQ4 (Methane) Sensors to be used on science robot. Links to the breakout boards [MQ135 CO2 Sensor](https://a.co/d/9x2vbe4) [MQ4 Methane Sensor](https://a.co/d/4Ii6J2Z). Create a PCB to interface with the Universal Controller Board

**Comment by swiftrax** [comment]
@Pinyiyeh @a3has do you guys want to pick up this project?

**Comment by Pinyiyeh** [comment]
Yeah sure

**Comment by a3has** [comment]
of course. I'll start today.

**Comment by swiftrax** [comment]
**Updated Task**
Design a PCB with a micromod controller for the science robot with the following:
- [x] 2 [dosing pumps](https://a.co/d/hQIwGGS) (one for buffer and reagent)
- [x] 1 [air pump](https://a.co/d/gJiZaC2)
- [x] 4 [hall effect sensor for checking position](https://a.co/d/b7AwY8U)
- [x] [270 degree rotation servo](https://a.co/d/hKmJIqQ) 
- [x] [360 degree rotation servo]()
- [x] 12V output for mini pc
- [x] the above mentioned sensors
