### ISSUE TITLE
RMD USBC Drive Breakout

### ISSUE THREAD

**Issue by swiftrax** [SJSURoboticsTeam/urc-electrical-2023#2]
USB C breakout for RMD X-6 S2 Motors 
[Motor Datasheet](https://www.myactuator.com/_files/ugd/cab28a_c3ece44cd47843a3852eb1606061adcc.pdf)
[USB C breakout connections](https://docs.google.com/document/d/1aVUD8fPPjsWwh0u0SxEuxSDWDWPMvqqYUcRhMcYtpVg/edit)
 
2x (turning and driving motors / slipring)
- [ ] VBatt
- [ ] CANH
- [ ] CANL
- [ ] GND
- [ ] Homing Pin

**Comment by swiftrax** [comment]
Homing pin connected to magnet switch. Other end of magnet switch is GND. Similar to this 
![image](https://user-images.githubusercontent.com/48102030/198864830-1d27c237-b656-4411-bcd0-6047aeea9625.png)

**Comment by a3has** [comment]
This is Revision A of the usb c breakout for the motors, please review it and double check our work. Feedback is greatly appreciated. 
There are some issues in this board we would love to get help with:
1- we were not able to find the correct phoenix headers for the homing pin and ground on easyEDA pro, we used a placeholder until it can be replaced (it unfortunately does not have 3D view also).
2- I think out vias are too small for the power lines, we could make them wide if needed.
-Aboudi & Dawinder
[ProProject_USB C BREAKOUT_2022-11-03.zip](https://github.com/SJSURoboticsTeam/urc-electrical-2023/files/9933761/ProProject_USB.C.BREAKOUT_2022-11-03.zip)

**Comment by a3has** [comment]
Board all done. 
TVS added
zero DRC errors
all traces are correct width.

Ready for final review before order.

**Comment by swiftrax** [comment]
good work!
