### ISSUE TITLE
Demultiplexer circuit testing

### ISSUE THREAD

**Issue by Pinyiyeh** [SJSURoboticsTeam/urc-electrical-2023#24]
The purpose of this testing is to make sure the PCA chip on the science board can be replaced in order to achieve higher frequency PWM.

**Comment by kammce** [comment]
Try using the the mux on the science board: CD74HC4067SM96E4.

**Comment by DolphinGui** [comment]
PWM is no longer being used to control the pumps.

For future reference: I suspect poor pwm performance is due to parasitic capacitance in the transistor, requiring a gate driver or something to provide higher current. Without further testing however, this is but speculation.
