### ISSUE TITLE
Universal Controller Rev C

### ISSUE THREAD

**Issue by swiftrax** [SJSURoboticsTeam/urc-electrical-2023#26]
- [x] CANBUS [Single Ended](https://github.com/SJSURoboticsTeam/urc-electrical-2023/issues/23) using TXP/N and RXP/N instead of DP and DN
- [x] Normally closed gate for power to CAN Transceiver
- [ ] Relay for motor power
- [x] Testpoints for all used signals
- [x] Single pin header holes for GND (Testpoint)
- [x] Ability to swap TX / RX for CANBUS / UART
- [x] Move from 1.27mm IDC Connector to 2.54mm 
- [x] Use CANRD or CANTD for Debug pin instead of CANL
~~Active Suspension (DRV8801?) TBD~~
~~3x MPU? TBD~~

**Comment by swiftrax** [comment]
What is the maximum torque/power the wheels will have to undergo to go up a 30deg hill? @theblueone111 or someone else in mechanical

**Comment by swiftrax** [comment]
[Voltage / Current of drive system spreadsheet](https://docs.google.com/spreadsheets/d/1rjap46mEMmu6xbYGVP59H703Efdyi7vM_CfQDMcfx6M/edit#gid=0)

**Comment by kammce** [comment]
- [x] Increase capacitance for regulator (same ripple issue as seen on the mimic was found on this board)
