### ISSUE TITLE
Drill Battery for rover power

### ISSUE THREAD

**Issue by swiftrax** [SJSURoboticsTeam/urc-electrical-2023#3]
Research how we can use a drill battery instead of the batteries we already have. Preferably with protections onboard.
Ryobio 40V 4Ah Lithium Ion Battery
[Amazon Drill battery](https://www.amazon.com/Ryobi-40V-Lithium-Ion-Battery-OP4040/dp/B07QYH36TC)

[Adapter Suggestion](https://www.amazon.com/Adapter-Lithium-ion-Battery-Connector-Robotics/dp/B07J17Z42R)

**Comment by swiftrax** [comment]
Battery ordered make a datasheet

**Comment by a3has** [comment]
Noted. Will make data sheets with diagrams, pin outs, documentation. Will pin and reference already existing data for the ryobi 40v 4ah op4040a1 battery.

**Comment by kammce** [comment]
@swiftrax please post the actual information here rather than referring to our discord channel. The github should be a source of truth for the team.

**Comment by a3has** [comment]
https://docs.google.com/document/d/1KqXAJnEpiBfd5Wi0-QqxNQPJysSO-6ZXHhX_RDiWdC8/edit?usp=sharing

**Comment by swiftrax** [comment]
good work! thanks!
