### ISSUE TITLE
Make kill switch PCB

### ISSUE THREAD

**Issue by swiftrax** [SJSURoboticsTeam/urc-electrical-2023#43]
Make a PCB that is for the kill switch to make it smaller using the following

- [ ] [Remote Switch](https://a.co/d/1UJ9zEK)
- [ ] [Push Switch](https://www.amazon.com/APIELE-Emergency-Latching-Stianless-Mouting/dp/B08QD31NNC/)
- [ ] [Inrush Thermistor](https://www.amazon.com/Aqua-Rite-Thermistor-2R025-Current-Limiter/dp/B071HX7XNY/ref=sr_1_3?keywords=inrush+current+limiter&qid=1691282520&sprefix=inrush+%2Caps%2C124&sr=8-3)
- [ ] [12V relay](https://www.lcsc.com/product-detail/_Ningbo-Songle-Relay-_C125736.html)

**Comment by swiftrax** [comment]
Ordered 2 of the parts listed above

**Comment by kammce** [comment]
Just a note that the inrush thermistor I found and listed in the first comment should work for our needs, but its quite expensive from Amazon. _Might_ be able to find some cheaper on digikey or mouser. I tried looking for them in LCSC but couldn't find them. Maybe they go under a different name on LCSC? I also cannot find any SMD versions of this, so through hole will definitely be the way to go as far as I can tell.

**Comment by kammce** [comment]
As for the relay, I wonder if there is a way to eliminate the need for the buck converter on this? 🤔 Just a thought, if such a scheme is too complicated then we can stick with the buck converters. Maybe having another inductor in series can add some resistance drop the voltage at the coil? But I'm not sure if that results in the more or less power consumption.

**Comment by swiftrax** [comment]
> As for the relay, I wonder if there is a way to eliminate the need for the buck converter on this? 🤔 Just a thought, if such a scheme is too complicated then we can stick with the buck converters. Maybe having another inductor in series can add some resistance drop the voltage at the coil? But I'm not sure if that results in the more or less power consumption.

The remote switch runs off 3.3V - 12V so I think we have to keep the buck on there

**Comment by kammce** [comment]
> > As for the relay, I wonder if there is a way to eliminate the need for the buck converter on this? 🤔 Just a thought, if such a scheme is too complicated then we can stick with the buck converters. Maybe having another inductor in series can add some resistance drop the voltage at the coil? But I'm not sure if that results in the more or less power consumption.
> 
> The remote switch runs off 3.3V - 12V so I think we have to keep the buck on there

Great point! Yeah, buck stays then :)

**Comment by swiftrax** [comment]
> Just a note that the inrush thermistor I found and listed in the first comment should work for our needs, but its quite expensive from Amazon. _Might_ be able to find some cheaper on digikey or mouser. I tried looking for them in LCSC but couldn't find them. Maybe they go under a different name on LCSC? I also cannot find any SMD versions of this, so through hole will definitely be the way to go as far as I can tell.

Couldn't find SMD versions of these either, was able to find a cheaper version the SL32 but from what I've read its weaker than the AS32. Price is about the same on Amazon vs Digi ($7 Amazon / $7 Digi) but Amazon is cheaper because shipping.

**Comment by swiftrax** [comment]
[Analog Switch to lower power consumption](https://www.analog.com/en/technical-articles/analog-switch-lowers-relay-power-consumption.html#:~:text=On%20the%20other%20hand%2C%20the,lower%20voltage%20(Figure%201).)
We can do something like this and throw a 3.3V regulator since the drop out voltage is around 1.2V. 
@kammce

**Comment by kammce** [comment]
Thats not a bad idea 😄 We just need to verify that a steady 3v3 on the coil will actuate it well.

**Comment by swiftrax** [comment]
There's two ways we can do this:
- Figure out relay holding current
- Switch voltages using the 3V3 Regulator
![image](https://github.com/SJSURoboticsTeam/urc-electrical-2023/assets/48102030/a867ccc4-b65f-48fd-9dbf-538f571c335b)

**Comment by swiftrax** [comment]
Components and circuit verified. Schematic made pending review then going to layout and route pcb to mechanical's specification. (@MayaEnriquez )

**Comment by DolphinGui** [comment]
This is now the stop sign kill switch PCB.
