### ISSUE TITLE
ESP32 Camera

### ISSUE THREAD

**Issue by swiftrax** [SJSURoboticsTeam/urc-electrical-2023#47]
Make board to interface with ESP32 Sense board and a BP70A battery
[Xiao ESP32 Sense](https://www.aliexpress.us/item/2255799825490363.html)

- [ ] Camera Mounting holes
- [ ] Battery compartment
- [ ] Access to USB C / Micro SD

Quality of Life
- [ ] ? Switch for On / Off
- [ ] ? Low Battery LED indicator

https://github.com/SJSURoboticsTeam/URC-Mechanical-2023/issues/47

**Comment by swiftrax** [comment]
@MayaEnriquez we might need help with coming up with a case / PCB for this project

**Comment by swiftrax** [comment]
![image](https://github.com/SJSURoboticsTeam/urc-electrical-2023/assets/48102030/544d4900-0d38-4ac0-8f73-9f4b5a6ff73c)

Connector [LCSC P0.5 24Pin](https://www.lcsc.com/product-detail/_Shenzhen-Kinghelm-Elec-_C2797213.html)

**Comment by swiftrax** [comment]
[Possible Mounting Solution](https://a.co/d/2T1jpuD)
[Quick Release Mount](https://a.co/d/iARgRxp)

**Comment by swiftrax** [comment]
Need to find a place for the antenna 

Alternative U.FL Antennas
[Long](https://www.lcsc.com/product-detail/Antennas_BAT-WIRELESS-BW2-4FNX26-10B1_C496563.html)
[Big Rectangle](https://www.lcsc.com/product-detail/Antennas_BAT-WIRELESS-BW433FNX75-35B1_C496562.html)
[Wide](https://www.lcsc.com/product-detail/Antennas_BAT-WIRELESS-BW2-4FNX42-12B1_C496564.html)

**Comment by swiftrax** [comment]
@tommytn54

**Comment by DolphinGui** [comment]
The ESP-cam is nearly complete now, and due to time constraints utilizes an COTS esp board modified with a battery connector.
