### ISSUE TITLE
Drill battery for rover power (current design SJDev2)

### ISSUE THREAD

**Issue by swiftrax** [SJSURoboticsTeam/urc-electrical-2023#7]
Check if 1 additional lipo cell will break any of the circuits on the existing boards
- [ ] Unified Controller Board
- [ ] ...

**Comment by kammce** [comment]
We should make a separate issue for disposing of the old batteries.

**Comment by swiftrax** [comment]
@kammce done! If you want you can also open issues if you see something that needs to be done.

**Comment by kammce** [comment]
Of course but I'd rather leave that work to your team @swiftrax
