### ISSUE TITLE
Dispose of old batteries

### ISSUE THREAD

**Issue by swiftrax** [SJSURoboticsTeam/urc-electrical-2023#9]
Dispose of old batteries as we shift to the drill batteries 
Santa Clara County Household Hazardous Waste facility 
- [ ] Lipo
- [ ] Alkaline
- [ ] ...

**Comment by swiftrax** [comment]
@Coreyboy1820 @kammce do you guys want to do this next weekend? Or would we add these as for sale to senior projects?

**Comment by kammce** [comment]
There are batteries we should definitely should dispose of and not give to others. But the unused ones can be given in the garage sale.
